spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db3?serverTimezone=Asia/Shanghai&&characterEncoding=UTF-8
    username: root
    password: 123456

server:
  port: 8122

DB_path:
  path: D:\UploadDownload\REC